name: test_gh_authenticate_action
on:
  pull_request:
    types: ['opened']

jobs:
  action-check-pr:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

# Extracting Ticket Number from triggered PR event  


    - name: Capture Triggered PR
      run: |
        cpr=$(gh pr view  $PR --jq=.title --json=title)
        echo $cpr
        if [[ $cpr =~ (prodsup|PRODSUP|Prodsup|ProdsUp)  ]]; then echo "yay" ; fi



      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
    
