name: test_gh_authenticate_action
on:
  pull_request:
    types: ['opened']

jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Capture Triggered PR
      run: |
        lpr=$(gh pr list -s open | awk '{$1=$(NF-1)=$NF=""; print $0}' | head -1 | egrep  "( *[a-zA-Z]{1,7}\-[0-9]{1,7} *)" | wc -l)
        echo $lpr
        if [ $lpr -eq 0 ]; then gh pr comment "$PR" --body "Please add ticket to this PR!"; fi
#        gh pr comment "$PR" --body "Thank you for opening this issue!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
    
