name: test_gh_authenticate_action
on:
  pull_request:
    types: ['opened']

jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Capture Triggered PR
      run: |
        latest_pr_opened=`gh pr list -s open | awk '{$1=$NF=""; print $0}' | head -1`
        gh pr comment "$PR" --body "Thank you for opening this issue!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
    
