on:
  pull_request:
    types: ['opened']

jobs:
  pr_name_check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

##########################################################################################################################################
#                                                                                                                                        #
# This Action checks the following condition and updates the PR title appropriately.                                                     #
#     1. EITHER VALID JIRA TICKET IS PRESENT IN THE TITLE OF THE PR                                                                      #
#   T  2. OR VALID JIRA TICKET IS PRESENT IN THE BRANCH NAME OF THE PR ADD THAT TICKET NUMBER TO PR TITLE                                 #
#  T   3. IF BOTH OF THE ABOVE SCENORIOS ARE MISSING ADD A COMMENT TO PR TO ASSOCIATE A TICKET IN THE PR TITLE                            #
#  T   4. IT DOES NOT WARN FOR ANY PR THAT IS MERGING DOWN DIRECTLY FROM RELEASE_CANDIDATE TO PREVIEW AND PREVIEW TO RELEASE_CANDIDATE   THE BRANCH NAME BEGINS WITH NAME LIKE "merge_prev_dev_xyz"  # Checked
#  T   5. IT DOES NOT WARN FOR ANY PR FOR WHICH THE BRANCH NAME IS PREVIEW OR RELEASE_CANDIDATE    TEsted                           
#                                                                                                                                        #
#                                                                                                                                        #
# OPS-1938 https://mindbridge-ai.atlassian.net/browse/OPS-1938                                                                           #
#                                                                                                                                        #
##########################################################################################################################################

    - name: Capture Triggered PR
      run: |
        branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
        echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
        a_n=${{ github.event.pull_request.user.login }}
        gh pr comment "$PR" --body "There are conflicts while merging the $base down to @$a_n. Please resolve the conflicts manually. "

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
        
