name: test_gh_authenticate_action
on:
  pull_request:
    types: ['opened']

jobs:
  gh-cli-pr-view:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Capture Triggered PR
      run: |
        branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName)
        echo $branch_name
#        ticket_number=$(egrep ([a-zA-Z]{1,5}\-[0-9]{1,6}) $branch_name ) 
#        echo $ticket_number
#        gh pr view "$PR"
#        lpr=$(gh pr list -s open | awk '{$1=$(NF-1)=$NF=""; print $0}' | head -1 | egrep  "( *[a-zA-Z]{1,5}\-[0-9]{1,6} *)" | wc -l)
#        echo $lpr
#        echo $lpr
#        OPS-101-gr-pr-view-1
#        echo $lpr
#       if [ $lpr -eq 0 ]; then gh pr comment "$PR" --body "Please add ticket to this PR!"; fi
#        gh pr comment "$PR" --body "Thank you for opening this issue!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
    
