name: gh_action_pr_title_check
on:
  pull_request:
    types: ['opened']

jobs:
  action-check-pr-checkTitle:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

###########################################################################################################################
#                                                                                                                         #
# This Action checks the following condition and updates the PR title appropriately.                                      #
#     1. If the ticket is ProdsUP then ignore updating the PR tite and add a comment to associate AIA ticket with PRODSUP #
#     2. Every ticket should contain the corresponding AIA-XXXX / OPS-XXXX / AXIOME-XXXXX                                 #
#                                                                                                                         #
# Check if PRODSUP ticket has AIA-XXXX mentioned in title                                                                 #
#                                                                                                                         #
# OPS-1938 https://mindbridge-ai.atlassian.net/browse/OPS-1938                                                            #
#                                                                                                                         #
###########################################################################################################################

    - name: Capture Triggered PR
      run: |
        branch_name=$(gh pr view  $PR --jq=.headRefName --json=headRefName | tr "_" "-")
        valid_ticket_in_branch_name=0
        subString1=$(echo "$branch_name" | cut -d'-' -f 1)
        jira_project_from_branch_name=$(echo "$subString1" | tr a-z A-Z)
        case "$jira_project_from_branch_name" in
          AIA|OPS|AXIOME)
            valid_ticket_in_branch_name=1
            ;;
        esac
        subString2=$(echo "$branch_name" | cut -d'-' -f 2)
        if ! [[ "$subString2" =~ ^[0-9]+$ ]]
        then
          valid_ticket_in_branch_name=0
        fi
        title=$(gh pr view  $PR --jq=.title --json=title)
        title_dashes=$(echo "$title" | tr "_: " "-")
        valid_ticket_in_branch_name=0
        subString3=$(echo "$title_dashes" | cut -d'-' -f 1)
        jira_project_from_branch_name=$(echo "$subString3" | tr a-z A-Z)
        case "$jira_project_from_title" in
          AIA|OPS|AXIOME)
            valid_ticket_in_title=1
            ;;
        esac
        subStringr4=$(echo "$title_dashes" | cut -d'-' -f 2)
        if ! [[ "$subStringr4" =~ ^[0-9]+$ ]]
        then
          valid_ticket_in_title=0
        fi
        echo $valid_ticket_in_title
        echo $valid_ticket_in_branch_name
        if [ "$valid_ticket_in_title" -eq 1  ]
        then
          exit 0
        elif [ "$valid_ticket_in_title" -eq 0  ]
        then
          if [ "$valid_ticket_in_branch_name" -eq 1  ]
          then
            ticket_number_from_branch=$(echo "$subString1-$subString2")
            echo "$ticket_number_from_branch"
            gh pr edit "$PR" -t "$ticket_number_from_branch $title" 
          else 
            gh pr comment "$PR" --body "Please add an AIA Jira ticket to the title of this pull request so we can track it for change management and to make it easier to find during annual audits. Pull requests for this repository should be tied to one or more Jira tickets."
          fi
        fi
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.number }}
